#!/bin/bash
DISK=/tmp/disk
QEMU=/tmp/qemu/bin/qemu-system-loongarch64
[ -e $DISK ] || { truncate -s 32M $DISK;echo -e 'n\n\n\n\n\n\nw\nq\n'| fdisk /tmp/disk; }

ls2k()
{
BIOS=/tmp/qemu/share/qemu/gzrom-dtb-la2k.bin
BIOS=./2k1000/u-boot-with-spl.bin
DEBUG_GMAC_PHYAD=0 $QEMU -M ls2k -serial stdio -serial vc -drive if=pflash,file=$BIOS  -m 1024 -device usb-kbd,bus=usb-bus.0 -device usb-tablet,bus=usb-bus.0  -device usb-storage,drive=udisk -drive if=none,id=udisk,file=$DISK -net nic -net user,net=10.0.2.0/24,tftp=/srv/tftp -vnc :0  -D /tmp/qemu.log -s "$@" 2>&1 -hda ./2k1000/2kfs.img
}

ls2k "$@"
