#!/bin/bash
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
ln -sf "$SCRIPTPATH"  /tmp/qemu
DISK=/tmp/disk
QEMU=/tmp/qemu/bin/qemu-system-loongarch64
TFTP_DIR="$SCRIPTPATH"/../../easy-fs-fuse
OS="$SCRIPTPATH"/nand.dat
[ -e "$OS" ] || dd if=/dev/zero bs=1M count=$(((256*(2048+64)/2048)))|tr '\000' '\377' > "$OS"
[ -e $DISK ] || { truncate -s 32M $DISK;echo -e 'n\n\n\n\n\n\nw\nq\n'| fdisk /tmp/disk; }

ls2k()
{
BIOS=/tmp/qemu/share/qemu/gzrom-dtb-la2k.bin
BIOS=${SCRIPTPATH}/2k1000/u-boot-with-spl.bin
DEBUG_GMAC_PHYAD=0 $QEMU -M ls2k -drive if=pflash,file=$BIOS  \
                         -m 2048M \
                         -D ${SCRIPTPATH=}/qemu.log \
                         -serial stdio \
                         -drive if=mtd,file="$OS"  \
                         -net nic -net user,net=192.168.1.2/24,tftp=$TFTP_DIR \
                         -net nic -net user,net=10.0.3.0/24\
                         -vnc :0   \
                         -serial vc \
                         -device usb-kbd,bus=usb-bus.0 \
                         -device usb-tablet,bus=usb-bus.0 \
                         -device usb-storage,drive=udisk \
                         -drive if=none,id=udisk,file=$DISK \
                         -s "$@" 2>&1 \
                         -hda ${SCRIPTPATH}/2k1000/2kfs.img
}
ls2k "$@"
